### ISSUE TITLE
ondataavailable is not triggered anymore in Chrome

### ISSUE THREAD

**Issue by ohjimijimijimi** [streamproc/MediaStreamRecorder#105]
Using the code shown here https://github.com/streamproc/MediaStreamRecorder#record-audiovideo to record audio and video the ondataavailable event is not triggered anymore making impossible to access the recorded blobs. 

This issue happens using the MediaRecorder API

Also, any of the example demo are working anymore.

To recreate the issue:
1. open one of the demo, for examplehttps://www.webrtc-experiment.com/msr/video-recorder.html
2. open the console 
3. start recording
4. stop recording
5. try to save
6. an error will appear in the console at line 110 of MediaStreamRecorder.js. Cannot access blobs object because undefined.

Any help or ideas?
Really appreciated!

**Comment by ohjimijimijimi** [comment]
As a workaround I forced the `WhammyRecorder` when browser is Chrome. This can be achieved with the following code:

```
var mediaRecorder = new MediaStreamRecorder(stream);
var isChrome = /* your preferred detection method */
if (isChrome) {
  self.mediaRecorder.recorderType = MediaStreamRecorder.WhammyRecorder;
}
```

**Comment by lehno** [comment]
Same problem here

**Comment by ohjimijimijimi** [comment]
it seems this issue does not happen anymore.

**Comment by stevula** [comment]
I am having this issue in Chrome with the [A/V example](https://github.com/streamproc/MediaStreamRecorder#record-audiovideo). It worked for me in Firefox.

**Comment by muaz-khan** [comment]
@stevula please test this demo:

* https://www.webrtc-experiment.com/msr/video-recorder.html
