### ISSUE TITLE
mimeType = "video/mp4" doesn't work

### ISSUE THREAD

**Issue by otiai10** [streamproc/MediaStreamRecorder#117]
Hi, this project helps me a lot, thank you very much.

# Summary:

~~I successfully can create blob url of mp4 and that URL is able to be played on Chrome, but once I downloaded it, it's not playable for QuickTime Player.~~

(Regarding [this truth](https://github.com/streamproc/MediaStreamRecorder/issues/117#issuecomment-280647263), I changed the issue summary)

Even when I give recorder mimeType with `"video/mp4"`, the generated file is `webm`, as ffmpeg said. That causes that I cannot play that video on QuickTime Player nor upload to Twitter.

# Reproducibility:

- 100%
- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"`
- Here is an example product to reproduce this problem https://github.com/otiai10/msr-debug

```javascript
const main = () => {
  console.log('MediaStreamRecorder:', typeof MediaStreamRecorder);
  navigator.getUserMedia({audio:false, video:true}, (stream) => {

    var recorder = new MediaStreamRecorder(stream);
    // recorder.mimeType = 'video/mp4';
    recorder.mimeType = 'video/mp4; codecs="avc1.42E01E, mp4a.40.2"';
    recorder.width    = 800;
    recorder.height   = 480;

    recorder.ondataavailable = (blob) => {
      const url = URL.createObjectURL(blob);
      // It works, looks good.
      window.open(url);

      // When I downloaded it as a file,
      var a = document.createElement('a');
      a.href = url;
      a.download = 'msr-example.mp4';
      a.click();
      // successful, but not playable on QuickTime Player
    };

    // Record it for 3s
    recorder.start();
    setTimeout(() => recorder.stop(), 3000);

  }, (err) => {
    console.error('getUserMedia failed', err);
  });
};

window.onload = main;
```

# Screen Shots:

Console

<img src="https://cloud.githubusercontent.com/assets/931554/23016949/a7957f42-f438-11e6-95b9-300509f720e1.png" width="80%">

working and playable on Chrome
<img src="https://cloud.githubusercontent.com/assets/931554/23016851/57a3852e-f438-11e6-9f9b-f3a83e5e95e8.png" width="40%">

not playable on QuickTime
<img src="https://cloud.githubusercontent.com/assets/931554/23016859/5d695a88-f438-11e6-9f3b-c104f1fc0bd4.png" width="40%">

# Comment:

I also found https://github.com/streamproc/MediaStreamRecorder/issues/69 and I assumed that is because codec support of QuickTime. I'm not familiar with binary/blob/encode/decode stuff, therefore any of your advise would be helpful for me. Thank you again.

cc @muaz-khan

**Comment by otiai10** [comment]
```sh
% ffmpeg -i ~/Downloads/msr-example.mp4
#
# here omitted by me ...
#
Input #0, matroska,webm, from '/Users/otiai10/Downloads/msr-example.mp4':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
At least one output file must be specified
```

it seems to be `webm`, doesn't it work with `recorder.mimeType = "video/mp4"`?

**Comment by otiai10** [comment]
let me change title

**Comment by otiai10** [comment]
Finally I concluded that this was my misunderstanding. Sorry for asking such nonsense question.

Thank you anyway.

**Comment by stevula** [comment]
What was your misunderstanding @otiai10 ? I'm having a similar issue.

**Comment by levinunnink** [comment]
What is the point of `recorder.mimeType = 'video/mp4';` if mp4 encoding isn't supported?

**Comment by playahater** [comment]
I'm having the same issue. Whichever mimeType I set, i get 
```Video: vp8, Audio: opus```

```javascript
     constructor(stream, mimeType = 'video/mp4') {
          this.stream = stream;
          this.recorder = new MediaStreamRecorder(this.stream);
          this.recorder.mimeType = mimeType;
          this.blob = null;
          this.delta = 20 * 60 * 60 * 1000;
          this.recorder.ondataavailable = data => { 
              this.blob = data;
          };   
          this.isStarted = false;
      } 
```

I've tried with different codecs options, but Chrome keeps setting webm.
I get log in console that mp4 has been passed to MediaRecorder as well.
Any hint on what am i doing wrong ?

**Comment by jcorkhill** [comment]
@otiai10 @playahater Did you ever find a solution to your issues? I'm having a similar problem.

**Comment by mzalen** [comment]
I haven't found any clear answers (other than to use ffmpeg to convert webm to mp4), but I found this interesting [thread](https://github.com/collab-project/videojs-record/issues/92).
