### ISSUE TITLE
onstop()

### ISSUE THREAD

**Issue by omarzion** [streamproc/MediaStreamRecorder#122]
it looks like the only place onstop() is called is in FlashAudioRecorder.js  could you add the onstop() callback for other recorders?

**Comment by varenc** [comment]
I'm finding this too.

Something I don't understand about this project is that the API seems to assume that most people know how long they want to record media before they start.  A common use case is to let the user decide when to start and when to stop recording.  Does this add some new technical difficulty? Are there any examples of that working well somewhere? Without onstop this is hard to do as well.

**Comment by omarzion** [comment]
I looked into the code and the onstop just hasn't been implemented elsewhere.  It looks like this project is several different ones thrown together and this particular call back is only implemented in one of the sub modules

**Comment by varenc** [comment]
without onstop, how do you record video/audio if you don't know the length of what you're recording before you start? building something that only records for a fixed amount of time seems like something you'd build as a demo, but not something you'd build into an actual product.  Gonna just look in to using MediaRecorder directly (where onstop is implemented...)

**Comment by omarzion** [comment]
I wasn't able to find where to add onstop to contribute to this project, and wasn't able to get it to work the way i was trying to use it..  i ended up changing the library i was using 3 or 4 times until i finally found RecordRTC and it suited my use case perfectly.  https://www.webrtc-experiment.com/RecordRTC/

**Comment by varenc** [comment]
thanks for the tip! I was a bit worried about that one was trying to do too much and I couldn't find any super great docs and examples for it. That said it sounds like I should give it another look.

also a bit confused since the maintainer of recordrtc and this project are the same person. =P

**Comment by omarzion** [comment]
Haha i hadn't noticed that.

**Comment by muaz-khan** [comment]
Seems a bug here.

* [common/MediaStreamRecorder.js#L48](https://github.com/streamproc/MediaStreamRecorder/blob/master/common/MediaStreamRecorder.js#L48)

I'll fix soon.

**Comment by incubusknight** [comment]
It's hard to know the specific use case you're trying to solve with the .onstop event, but I've implemented this library successfully (before this fix) for dynamic length recording and streaming by using the .ondataavailable event.

When the recorder's .stop() method is invoked, the ondataavailable event gets fired.

**Comment by muaz-khan** [comment]
According to the spec, `onstop` event should be fired only if you invoke `stop` method.

Which means that:

1. MediaRecorder state changes to `inactive` (means that no more recording); i.e. clear the intervals/timeouts/timeSlice passed over/via `start` method
2. Fire `dataavailable` event on last time (if browser still has data)

`stop` and `requestData` methods works same except that the later one (requestData) keeps recording and firing `dataavailable` events.

**This library (MediaStreamRecorder.js) is doing the same.**
