### ISSUE TITLE
project is generally broken and is not being actively supported

### ISSUE THREAD

**Issue by varenc** [streamproc/MediaStreamRecorder#131]
maintainers should update the readme to make it clear that this project isn't being supported! From the issues reported you can see that several pieces of the functionality described in the docs aren't actually working and cross-browser issues abound. 

Making the lack of support clear might inspire others to take up the mantle and get this project in order.  This is still a great foundation.

**Comment by muaz-khan** [comment]
"onstop" issue has been resolved. Is there anything else still not working?

**Known limitations:**

1. Video track recording is NOT supported on Microsoft Edge; only audio track is available in the moment.
2. No support for IE+Safari
3. Firefox (the browser itself) has a bug regarding `pause/resume` (works OK in Chrome, though)

**Comment by muaz-khan** [comment]
Please reopen this if you find broken implementations or bugs/issues.

**Comment by varenc** [comment]
@muaz-khan thanks for getting back to this! clearly, the project isn't fully abandoned but I do think there are some quality issues.  The audio demo linked to in the README is just broken it seems.

Steps to reproduce:
1. Go to https://www.webrtc-experiment.com/msr/audio-recorder.html in Chrome
2. Leave it on [Best Available Recorder] and click "Start"
3. Click stop
4. Click save

**Expected Results**
A .ogg audio file is saved

**Actual Results**
nothing is saved and this JavaScript error appears in the console
```MediaStreamRecorder.js:110 Uncaught TypeError: Cannot read property 'type' of undefined
    at MediaStreamRecorder.save (MediaStreamRecorder.js:110)
    at HTMLButtonElement.document.querySelector.onclick (audio-recorder.html:142)```

Though it should be noted that saving .wav files does indeed work. I'm particularly instead in getting something (anything!) better than a .wav so a broken demo immediately made me have concerns about the project.  The "tests" folder modified 4 years ago isn't a great sign either.  Of course, there's a lack of clear better option for me which is why I'm still here =)

**Comment by varenc** [comment]
I narrowed down this problem...ondataavilable just isn't being called in this case.  I added more info to #130

**Comment by varenc** [comment]
@muaz-khan the audio demo using the MediaRecorder API is still broken.  https://www.webrtc-experiment.com/msr/audio-recorder.html

It's a disservice to users that discover this project to have them struggle with something that isn't working.

**Comment by itdpong** [comment]
agree with varenc, I only want to record the audio only. So I follow the script in your audio demo, but actually it won't works(by the way, your demo is work, but the 'How to use?' part is not work)

```
var mediaConstraints = {
    audio: true
};

navigator.getUserMedia(mediaConstraints, onMediaSuccess, onMediaError);

function onMediaSuccess(stream) {
    var mediaRecorder = new MediaStreamRecorder(stream);
    mediaRecorder.mimeType = 'audio/webm'; // audio/webm or audio/ogg or audio/wav
    mediaRecorder.ondataavailable = function (blob) {
        // POST/PUT "Blob" using FormData/XHR2
        var blobURL = URL.createObjectURL(blob);
        document.write('<a href="' + blobURL + '">' + blobURL + '</a>');
    };
    mediaRecorder.start(3000);
}

function onMediaError(e) {
    console.error('media error', e);
}
```

but it do works if I change it to video format like this

```
var mediaConstraints = {
    audio: true,
    video:true
};

navigator.getUserMedia(mediaConstraints, onMediaSuccess, onMediaError);

function onMediaSuccess(stream) {
    var mediaRecorder = new MediaStreamRecorder(stream);
    mediaRecorder.mimeType = 'video/webm'; // audio/webm or audio/ogg or audio/wav
    mediaRecorder.ondataavailable = function (blob) {
        // POST/PUT "Blob" using FormData/XHR2
        var blobURL = URL.createObjectURL(blob);
        document.write('<a href="' + blobURL + '">' + blobURL + '</a>');
    };
    mediaRecorder.start(3000);
}

function onMediaError(e) {
    console.error('media error', e);
}
```

So could any one how to solve this????

**Comment by varenc** [comment]
@muaz-khan you mentioned that we should re-open if we find broken implementations, and as demonstrated audio support has been broken for at least 5-6 months.

**Comment by gregorydickson** [comment]
+1

**Comment by muaz-khan** [comment]
@varenc @gregorydickson please check #151.
