### ISSUE TITLE
MultiStreamRecorder can't replay audio on second recording session

### ISSUE THREAD

**Issue by hansman** [streamproc/MediaStreamRecorder#32]
I have a sample application that acquires local media and records audio and video. On user click 'replay' the just recorded blobs are replayed. When acquiring local media the second time to record and replay the audio/video blobs, audio is missing. This has been tested on Chrome.

Please take a look at the fiddle
https://jsfiddle.net/ufpeak2x/
1) run the fiddle
2) press 'replay'
3) press 'rerecord'
4) press 'replay'

Chrome Version 41.0.2272.104 (64-bit), Mac

**Comment by kapv89** [comment]
Facing the same issue

**Comment by probil** [comment]
The same issue. Audio records and plays for the first time but not working after stream.stop()

Chrome 44.0.2403.130 (64-bit), Linux
