### ISSUE TITLE
Long videos...

### ISSUE THREAD

**Issue by mullerivan** [streamproc/MediaStreamRecorder#35]
Hello im tring to record long videos en the browser, and then send it  to the server side.

When the videos are longer that 3 minutes, the videos start to be intermittent
looks like if some buffer get full because many frames get lost

im trying here:
https://www.webrtc-experiment.com/msr/video-recorder.html

Any idea  what could be the problem? maybe the browser buffer?

Edited:
I can see the same problem on the alternative project
https://www.webrtc-experiment.com/RecordRTC/

any suggestion ?

**Comment by rapofran** [comment]
May be this helps https://github.com/streamproc/MediaStreamRecorder/issues/21#issuecomment-69899706

**Comment by mullerivan** [comment]
well.... for me the problem was when recording the video and change the tab on my Brower....
that do lost the priority on the processors and start to lost frames....
