### ISSUE TITLE
Bad Gateway when trying to access cdn file

### ISSUE THREAD

**Issue by abhinaykumar** [streamproc/MediaStreamRecorder#37]
When I am trying to access cdn file from here `https://cdn.webrtc-experiment.com/MediaStreamRecorder.js` I see `502 Bad Gateway` error everytime.
Adding the screen shot below
![screenshot from 2015-05-28 18 03 40](https://cloud.githubusercontent.com/assets/4496810/7860129/e8b0682c-0563-11e5-8b13-974c12865ceb.png)

**Comment by muaz-khan** [comment]
Now CDN link is temporarily redirecting to `https://www.webrtc-experiment.com/*` instead.

MaxCDN based redirects will be fixed soon.

Previously it was working like this: `cdn.webrtc-experiment.com` redirects to MaxCDN, which services all static files from `www.webrtc-experiment.com`.

Now: `cdn.webrtc-experiment.com` directly redirects to `www.webrtc-experiment.com`.

```html
<script src="https://www.webrtc-experiment.com/MediaStreamRecorder.js"></script>
```

**Comment by abhinaykumar** [comment]
:+1: thank you
