### ISSUE TITLE
problem record audio only

### ISSUE THREAD

**Issue by vanbinh2811** [streamproc/MediaStreamRecorder#53]
I can't get blob audio http://jsfiddle.net/nvb1128/d3x7jbbt/ help me.

**Comment by muaz-khan** [comment]
Its working fine for me using Chrome, Firefox and Opera on both Mac and Windows (desktop platforms).

Can you please open "Console" tab from Developer tools and share console-logs? E.g.

```
using audio buffer-size: 2048
MediaStreamRecorder.js:492 All right-channels are skipped.
MediaStreamRecorder.js:393 audio recorded blob size: 254 KB
MediaStreamRecorder.js:393 audio recorded blob size: 393 KB
MediaStreamRecorder.js:393 audio recorded blob size: 381 KB
```

**Comment by vanbinh2811** [comment]
I runing chrome. Console logs just write All right-channels are skipped after stop nothing console KB as on

**Comment by vanbinh2811** [comment]
Console chrome of me:
using audio buffer-size: 2048
MediaStreamRecorder.js:492 All right-channels are skipped.

**Comment by vanbinh2811** [comment]
Console chrome of me:
using audio buffer-size: 2048
MediaStreamRecorder.js:492 All right-channels are skipped.

**Comment by muaz-khan** [comment]
Please try this demo ( https://www.webrtc-experiment.com/msr/audio-recorder.html ) and uncheck `Only Left Channel` checkbox to make sure it records both left/right channels.

**Comment by vanbinh2811** [comment]
that work. thank you
