### ISSUE TITLE
mediaRecorder.onstop doesn't fire

### ISSUE THREAD

**Issue by mlaco** [streamproc/MediaStreamRecorder#56]
I have a setup much like the demo, and `ondataavailable` does fire, but `onstop` does not.

**Comment by jonrscott** [comment]
i have the same problem

**Comment by cpruijsen** [comment]
same problem

**Comment by szc001** [comment]
same :(

**Comment by benhonna** [comment]
Same.  Anyone have a solution?

**Comment by omarzion** [comment]
I looked through some of the source and it looks like onstop is only called from FlashAudioRecorder.  I think onstop would have to originate in whammy.compile in VideoStreamRecorder/lib/whammy.js which uses a webworker.

**Comment by morgandonze** [comment]
Closing because I'm not using this anymore.
