### ISSUE TITLE
[SOLVED] How to remove the recording icon after clicking stop(); ?

### ISSUE THREAD

**Issue by davidsadan** [streamproc/MediaStreamRecorder#76]
I am using the MediaStreamRecorder.js library for audio capture with Javascript. Almost everything is ok. The only problem I am finding is that when I click on Stop to stop recording the red recording icon is still up there, on the tab. Anyone know how I remove this icon when you click Stop?

Example in jsFiddle: [https://jsfiddle.net/davidsadan/wazb1jks](https://jsfiddle.net/davidsadan/wazb1jks)

Here is the print of how it is when I click Stop

![zka12](https://cloud.githubusercontent.com/assets/12474863/13852123/935c5e3a-ec3f-11e5-97ed-186d92a5c068.png)

**Comment by muaz-khan** [comment]
Please check this: https://jsfiddle.net/wazb1jks/3/

```javascript
navigator.getUserMedia(mediaConstraints, function(stream) {
    window.streamReference = stream;
    onMediaSuccess(stream);
}, onMediaError);

function stopStream() {
    if (!window.streamReference) return;

    window.streamReference.getAudioTracks().forEach(function(track) {
        track.stop();
    });

    window.streamReference.getVideoTracks().forEach(function(track) {
        track.stop();
    });

    window.streamReference = null;
}
```

**Comment by davidsadan** [comment]
Thans

**Comment by davidsadan** [comment]
Very Thanks, Muaz :)

Regards.

2016-03-18 5:43 GMT-03:00 Muaz Khan <notifications@github.com>:

> Please check this: https://jsfiddle.net/wazb1jks/3/
>
> navigator.getUserMedia(mediaConstraints, function(stream) {
>     window.streamReference = stream;
>     onMediaSuccess(stream);
> }, onMediaError);
> function stopStream() {
>     if (!window.streamReference) return;
>
>     window.streamReference.getAudioTracks().forEach(function(track) {
>         track.stop();
>     });
>
>     window.streamReference.getVideoTracks().forEach(function(track) {
>         track.stop();
>     });
>
>     window.streamReference = null;
> }
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/streamproc/MediaStreamRecorder/issues/76#issuecomment-198257580>
>



-- 
Atenciosamente,


[image: --]

David Damasceno
[image: https://]about.me/daviddamasceno
<https://about.me/daviddamasceno?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
