### ISSUE TITLE
Is not available at the mobile terminal?

### ISSUE THREAD

**Issue by wanlxz** [streamproc/MediaStreamRecorder#98]
When I use the browser to open the mobile terminal, I found that there is no response, simply can not record sound or video, I would like to ask why?

**Comment by 10pratik** [comment]
permission issues . Web browsers have those functionalities.mobiles are personal devices and thus the security levels are high.When u install apps then they ask for that permission tobe in ur mobile and use the camera.Sadly a browser isnt allowed to do that .
